# Site settings
title: 'soham kamani'
email: sohamkamani@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full stack web developer and electronics hobbyist. Especially interested in javascript, python, and IOT. Enjoys eating <span id="fruit-text"></span>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sohamkamani.com" # the base hostname & protocol for your site
twitter_username: sohamkamani
github_username:  sohamkamani

highlighter: pygments

permalink: blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
